var myArray = [{
        name: 'Touristic maps of Samegrelo Region. Spatial Promotional material for DMO',
        company: 'Destination Management Organization of Samegrelo Zemo Svaneti Regions',
        category: 'Tourism Cartography',
        year: '2019',
    },
    {
        name: 'Topographic Survey and Inventory plan of Vake Park Tbilisi',
        company: ' Chris Blandford Associates (UK), Tbilisi Mayor’s Office',
        category: 'topographic survey, plants inventory database',
        year: ' 2019 ',
    },
    {
        name: ' Touristic trails planning and mapping for Dusheti Area ',
        company: ' GIZ, Mountain Guides Association of Georgia ',
        category: ' Tourism, Spatial planning, Cartography ',
        year: ' 2019 ',
    },
    {
        name: 'Analysis of Climate Change Impact on Tourism and Recommendations for Climate Resilient Planning/Operation',
        company: 'World Bank',
        category: 'GIS, Mapping',
        year: '2018',
    },
    {
        name: 'Georgia National Action Plan for Adapting to Climate Change Impacts in the Black Sea Coastal Zone Analysis of Climate Change Impact on Infrastructure and Recommendations for Climate Resilient Planning/Operation',
        company: 'World Bank',
        category: 'GIS, Mapping',
        year: '2018',
    },
    {
        name: 'Preparation of Master Plan for “Tabakhmela Veli” Condomium',
        company: '“Tabakhmela Veli” Condomium',
        category: 'Urban Planning, GIS',
        year: '2017 ',
    },
    {
        name: 'Mapping of German Settlements Urban Areas.',
        company: 'Association for the  Preservation  of German Cultural Heritage in South Caucasus',
        category: ' Cartography, GIS data Management',
        year: '2015-2016',
    },
    {
        name: 'Waste Management Technology in Regions',
        company: 'CENN, The Solid Waste Management Company of Georgia',
        category: ' Spatial Database Server Management',
        year: '2017',
    },
    {
        name: 'Topographic Survey and Inventory plan of Tbilisi Botanic Garden',
        company: 'National Botanic Garden',
        category: 'Geodesy, Planning, Geography Database Management.',
        year: '2017',
    },
    {
        name: 'Touristic trails planning and mapping for Shida Kartli Region',
        company: 'Georgian National Tourism Administration',
        category: 'Tourism, Spatial planning, Cartography',
        year: '2017',
    },
    {
        name: 'Touristic trails planning and mapping for Samtskhe-Javakheti Region',
        company: 'Georgian National Tourism Administration',
        category: 'Tourism, Spatial planning, Cartography',
        year: '2016',
    },
    {
        name: 'Touristic trails planning and mapping for Rezort Utsera',
        company: 'GIZ, Mountain Guides Association of Georgia',
        category: 'Tourism, Spatial planning, Cartography',
        year: '2015',
    },
    {
        name: '----------------------',
        company: '---------------------',
        category: '-------------',
        year: '----',
    },
    {
        name: '----------------------',
        company: '---------------------',
        category: '-------------',
        year: '----',
    },
    {
        name: '----------------------',
        company: '---------------------',
        category: '-------------',
        year: '----',
    },
    {
        name: '----------------------',
        company: '---------------------',
        category: '-------------',
        year: '----',
    },
    {
        name: '----------------------',
        company: '---------------------',
        category: '-------------',
        year: '----',
    },
    {
        name: '----------------------',
        company: '---------------------',
        category: '-------------',
        year: '----',
    },
    {
        name: '----------------------',
        company: '---------------------',
        category: '-------------',
        year: '----',
    },
    {
        name: '----------------------',
        company: '---------------------',
        category: '-------------',
        year: '----',
    },
    {
        name: '----------------------',
        company: '---------------------',
        category: '-------------',
        year: '----',
    },
    {
        name: '----------------------',
        company: '---------------------',
        category: '-------------',
        year: '----',
    },
];